import { 
  Box, 
  Container, 
  Flex, 
  Link, 
  Stack, 
  VStack, 
  Image, 
  Text,
  Heading 
} from '@chakra-ui/react'
import Head from 'next/head'
import { Layout } from '../components/base/Layout'


export default function Home() {
  return (
    <>
      <Head>
        <title>Mike Filicetti: Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout hideNavBar={false}>
        <Container maxW="container.xl" centerContent px="0" h="calc(100% - 60px)">
          <Flex 
            direction="row" 
            justify="center"
            align="center"
            w="100%"
            textAlign="center"
            m="auto"
          >
            <VStack justifyContent={`center`} spacing="20px">
              <Heading variant={`small-caps`} size={`4xl`}>Mike Filicetti</Heading>
              <Stack direction={['column', 'row']} spacing={[`1rem`, `3rem`]} fontSize={[`l`, `xl`]} fontWeight={700}>
                <Box>
                  Frontend Software Engineer
                </Box>
                <Box>
                  Product Manager
                </Box>
                <Box>
                  UI/UX Wizard
                </Box>
              </Stack>
              {/* <Text fontSize={[`l`, `xl`]} fontWeight={700}>
                Frontend Software Engineer | Product Manager | UI/UX Wizard
              </Text> */}
              <Text fontSize={[`sm`, `md`]} py={[`3rem`, `1rem`]}>
                Crafting seamless UI/UX solutions to drive your business forward.
              </Text>
            </VStack>
          </Flex>
        </Container>
      </Layout>
    </>
  )
}
