import Head from 'next/head'
import { Layout } from '../components/base/Layout'


export default function Home() {
  return (
    <>
      <Head>
        <title>Mike Filicetti: Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout hideNavBar={false}>
        
      </Layout>
    </>
  )
}
